name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
            
      - name: Install dependencies
        run: npm install --prefix ./wp-content/plugins/readsonic
      
      - name: Build
        run: npm run build --prefix ./wp-content/plugins/readsonic

      - name: Create archive
        run: npm run package --prefix ./wp-content/plugins/readsonic -- ${{ github.ref_name }}

      - name: Set up GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install GitHub CLI
        run: |
          curl -L https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_linux_amd64.deb -o ghcli.deb
          sudo dpkg -i ghcli.deb
          gh --version

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} ./wp-content/plugins/readsonic/readsonic-${{ github.ref_name }}.zip:readsonic.zip --title "Release ${{ github.ref_name }}" 

