name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
            
      - name: Install dependencies
        run: npm install --prefix ./wp-content/plugins/readsonic
      
      - name: Build
        run: npm run build --prefix ./wp-content/plugins/readsonic
      
      - name: Extract version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      
      - name: Use version
        run: echo The version is ${{ steps.get_version.outputs.VERSION }}
      
      - name: Create Archive
        run: npm run zip --prefix ./wp-content/plugins/readsonic -- ${{ steps.get_version.outputs.VERSION }}
