name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
            
      - name: Install dependencies
        run: npm install --prefix ./wp-content/plugins/readsonic
      
      - name: Build
        run: npm run build --prefix ./wp-content/plugins/readsonic
