name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
            
      - name: Install dependencies
        run: npm install --prefix ./wp-content/plugins/readsonic
      
      - name: Build
        run: npm run build --prefix ./wp-content/plugins/readsonic
      
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
