name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
            
      - name: Install dependencies
        run: npm install --prefix ./wp-content/plugins/readsonic
      
      - name: Build
        run: npm run build --prefix ./wp-content/plugins/readsonic
      
      - name: Use version
        run: echo The version is ${{ github.event.release.tag_name }}
      
      - name: Create Archive
        run: npm run zip --prefix ./wp-content/plugins/readsonic -- ${{ github.event.release.tag_name }}
